---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: openshift-helloworld
    name: che-host
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: openshift-helloworld
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: openshift-helloworld
    name: che-data-volume
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: openshift-helloworld
    name: claim-che-workspace
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: openshift-helloworld
    name: che
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: openshift-helloworld
    template:
      metadata:
        labels:
          app: openshift-helloworld
      spec:
        containers:
        - env:
          - name: RESPONSE
            value: "Hello World!"
          image: openshift/hello-openshift
          name: che
          ports:
          - containerPort: 8080
            name: http
          volumeMounts:
          - mountPath: /tmp/test
            name: che-data-volume
        volumes:
        - name: che-data-volume
          persistentVolumeClaim:
            claimName: che-data-volume
    triggers:
    - type: ConfigChange
