---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: openshift-helloworld
    name: che-host
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: openshift-helloworld
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: openshift-helloworld
    name: che
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: openshift-helloworld
    template:
      metadata:
        labels:
          app: openshift-helloworld
      spec:
        containers:
        - env:
          - name: RESPONSE
            value: "Hello World!"
          image: openshift/hello-openshift
          name: che
          ports:
          - containerPort: 8080
            name: http
    triggers:
    - type: ConfigChange
